// All demo data is clearly labeled as simulation
// Used only when DEMO_MODE=true or API keys are not configured

export const DEMO_DELHI_LOCATIONS = [
  { id: "cp", name: "Connaught Place (Rajiv Chowk)", lat: 28.6328, lng: 77.2197, type: "Metro Station" },
  { id: "cybercity", name: "DLF Cyber City, Gurugram", lat: 28.4950, lng: 77.0889, type: "Business District" },
  { id: "airport", name: "IGI Airport Terminal 3", lat: 28.5562, lng: 77.1000, type: "Airport" },
  { id: "karolbagh", name: "Karol Bagh Metro Station", lat: 28.6531, lng: 77.1909, type: "Metro Station" },
  { id: "nmundka", name: "Nawada Metro Station", lat: 28.6202, lng: 77.0578, type: "Metro Station" },
  { id: "noida", name: "Noida City Centre", lat: 28.5760, lng: 77.3573, type: "Business District" },
  { id: "vasant", name: "Vasant Kunj", lat: 28.5224, lng: 77.1557, type: "Residential" },
  { id: "iffco", name: "IFFCO Chowk, Gurugram", lat: 28.4697, lng: 77.0781, type: "Metro Station" },
  { id: "huda", name: "Huda City Centre", lat: 28.4595, lng: 77.0266, type: "Metro Station" },
  { id: "dwarka", name: "Dwarka Sector 21", lat: 28.5531, lng: 77.0594, type: "Metro Station" },
  { id: "rohini", name: "Rohini West", lat: 28.7041, lng: 77.1105, type: "Residential" },
  { id: "nehru", name: "Nehru Place", lat: 28.5489, lng: 77.2517, type: "Commercial" },
  { id: "saket", name: "Saket Metro Station", lat: 28.5245, lng: 77.2066, type: "Metro Station" },
  { id: "lajpat", name: "Lajpat Nagar", lat: 28.5698, lng: 77.2385, type: "Commercial" },
  { id: "kashmere", name: "Kashmere Gate", lat: 28.6666, lng: 77.2280, type: "Metro Station" },
];

export const DEMO_ROUTES = [
  {
    id: "r-metro-1",
    label: "Metro",
    mode: "Metro",
    icon: "🚇",
    totalDurationMin: 42,
    totalDistanceKm: 18.2,
    totalFare: 60,
    co2Kg: 0.746,
    walkingMinutes: 12,
    transfers: 1,
    trafficLevel: "low",
    isRecommended: true,
    description: "Via Yellow Line → Magenta Line",
    steps: [
      { step: 1, mode: "Walk", from: "Your Location", to: "Rajiv Chowk Metro", duration: 6, distance: 0.4 },
      { step: 2, mode: "Metro", from: "Rajiv Chowk", to: "Hauz Khas", duration: 18, distance: 8.1, line: "Yellow Line" },
      { step: 3, mode: "Metro", from: "Hauz Khas", to: "Sikanderpur", duration: 14, distance: 7.5, line: "Magenta Line" },
      { step: 4, mode: "Walk", from: "Sikanderpur Metro", to: "DLF Cyber City", duration: 4, distance: 0.2 },
    ],
  },
  {
    id: "r-bus-1",
    label: "DTC Bus",
    mode: "Bus",
    icon: "🚌",
    totalDurationMin: 65,
    totalDistanceKm: 22.4,
    totalFare: 30,
    co2Kg: 1.994,
    walkingMinutes: 8,
    transfers: 1,
    trafficLevel: "high",
    isRecommended: false,
    description: "Route 534A → 611",
    steps: [
      { step: 1, mode: "Walk", from: "Your Location", to: "CP Bus Stop", duration: 4, distance: 0.3 },
      { step: 2, mode: "Bus", from: "CP", to: "Dhaula Kuan", duration: 35, distance: 12.0, line: "534A" },
      { step: 3, mode: "Bus", from: "Dhaula Kuan", to: "DLF Cyber City", duration: 22, distance: 9.8, line: "611" },
      { step: 4, mode: "Walk", from: "Bus Stop", to: "Office", duration: 4, distance: 0.3 },
    ],
  },
  {
    id: "r-cab-1",
    label: "Cab (Ola/Uber)",
    mode: "Cab",
    icon: "🚖",
    totalDurationMin: 38,
    totalDistanceKm: 21.8,
    totalFare: 320,
    co2Kg: 3.728,
    walkingMinutes: 2,
    transfers: 0,
    trafficLevel: "medium",
    isRecommended: false,
    description: "Direct door-to-door via NH-48",
    steps: [
      { step: 1, mode: "Cab", from: "Your Location", to: "DLF Cyber City", duration: 36, distance: 21.8, line: "Direct" },
      { step: 2, mode: "Walk", from: "Drop Point", to: "Office", duration: 2, distance: 0.1 },
    ],
  },
  {
    id: "r-multimodal-1",
    label: "Metro + Walk",
    mode: "Metro",
    icon: "🚇",
    totalDurationMin: 48,
    totalDistanceKm: 17.4,
    totalFare: 50,
    co2Kg: 0.713,
    walkingMinutes: 18,
    transfers: 0,
    trafficLevel: "low",
    isRecommended: false,
    description: "Via Blue Line, less walking overall",
    steps: [
      { step: 1, mode: "Walk", from: "Your Location", to: "Mandi House Metro", duration: 8, distance: 0.6 },
      { step: 2, mode: "Metro", from: "Mandi House", to: "Dwarka Sector 21", duration: 30, distance: 15.2, line: "Blue Line" },
      { step: 3, mode: "Walk", from: "Dwarka Sec 21", to: "Destination", duration: 10, distance: 1.6 },
    ],
  },
  {
    id: "r-auto-1",
    label: "Auto-Rickshaw",
    mode: "Auto",
    icon: "🛺",
    totalDurationMin: 52,
    totalDistanceKm: 19.5,
    totalFare: 185,
    co2Kg: 1.268,
    walkingMinutes: 2,
    transfers: 0,
    trafficLevel: "medium",
    isRecommended: false,
    description: "CNG auto, negotiated fare",
    steps: [
      { step: 1, mode: "Auto", from: "Your Location", to: "DLF Cyber City", duration: 50, distance: 19.5, line: "Direct" },
      { step: 2, mode: "Walk", from: "Drop Point", to: "Office", duration: 2, distance: 0.1 },
    ],
  },
];

export const DEMO_WEATHER = {
  city: "New Delhi",
  temperature: 32,
  feelsLike: 36,
  humidity: 58,
  condition: "Partly Cloudy",
  conditionCode: "partly_cloudy",
  windSpeed: 14,
  rainMm: 0,
  visibility: 8.5,
  aqi: 142,
  isRaining: false,
  hasAlert: false,
  isDemo: true,
};

export const DEMO_NEARBY = {
  hospitals: [
    { name: "AIIMS Delhi", distance: 2.1, phone: "011-26593308", lat: 28.5672, lng: 77.2100 },
    { name: "Safdarjung Hospital", distance: 3.4, phone: "011-26730000", lat: 28.5688, lng: 77.2064 },
    { name: "Ram Manohar Lohia Hospital", distance: 1.8, phone: "011-23365525", lat: 28.6348, lng: 77.2028 },
  ],
  police: [
    { name: "Connaught Place Police Station", distance: 0.6, phone: "011-23363636", lat: 28.6315, lng: 77.2192 },
    { name: "New Delhi Police Station", distance: 1.2, phone: "011-23747980", lat: 28.6402, lng: 77.2129 },
  ],
  pharmacies: [
    { name: "Apollo Pharmacy", distance: 0.3, phone: "1860-500-1066", lat: 28.6320, lng: 77.2180 },
    { name: "MedPlus Pharmacy", distance: 0.5, phone: "040-67006700", lat: 28.6335, lng: 77.2210 },
  ],
  evChargers: [
    { name: "NTPC EV Charger - CP", distance: 0.4, type: "CCS2 + AC", lat: 28.6330, lng: 77.2205 },
    { name: "Tata Power EV Hub", distance: 1.1, type: "DC Fast", lat: 28.6280, lng: 77.2115 },
  ],
};

export const DEMO_COMMUNITY_REPORTS = [
  {
    id: "cr-1",
    category: "Pothole",
    title: "Large pothole on Ring Road near ITO",
    description: "Deep pothole causing traffic slowdown, risk of vehicle damage",
    address: "Ring Road near ITO Flyover",
    lat: 28.6290,
    lng: 77.2456,
    upvotes: 23,
    status: "open",
    severity: "high",
    timeAgo: "2 hours ago",
    userName: "Priya S.",
  },
  {
    id: "cr-2",
    category: "Waterlogging",
    title: "Waterlogging at Minto Bridge underpass",
    description: "Severe waterlogging after last night rain, 2ft water level",
    address: "Minto Bridge Underpass, DDU Marg",
    lat: 28.6368,
    lng: 77.2295,
    upvotes: 67,
    status: "acknowledged",
    severity: "critical",
    timeAgo: "5 hours ago",
    userName: "Rahul M.",
  },
  {
    id: "cr-3",
    category: "Signal",
    title: "Broken signal at Ashram Chowk",
    description: "Traffic signal not functioning at Ashram Chowk intersection",
    address: "Ashram Chowk, Ring Road",
    lat: 28.5717,
    lng: 77.2488,
    upvotes: 15,
    status: "open",
    severity: "medium",
    timeAgo: "1 day ago",
    userName: "Amit K.",
  },
  {
    id: "cr-4",
    category: "Construction",
    title: "Roadworks blocking left lane - NH-48",
    description: "Unauthorized construction blocking traffic near Dhaula Kuan",
    address: "NH-48 near Dhaula Kuan flyover",
    lat: 28.5946,
    lng: 77.1726,
    upvotes: 31,
    status: "open",
    severity: "medium",
    timeAgo: "3 hours ago",
    userName: "Deepa R.",
  },
  {
    id: "cr-5",
    category: "Streetlight",
    title: "Street lights not working - Rohini Sector 3",
    description: "Entire stretch of 500m is dark since 3 days",
    address: "Rohini Sector 3, Main Road",
    lat: 28.7060,
    lng: 77.1080,
    upvotes: 8,
    status: "open",
    severity: "low",
    timeAgo: "3 days ago",
    userName: "Sunita T.",
  },
];

export const DEMO_ALERTS = [
  {
    id: "a-1",
    type: "metro",
    title: "Delhi Metro Yellow Line Delay",
    message: "Trains delayed by 8-12 min between Vishwavidyalaya and Kashmere Gate due to technical snag",
    severity: "warning",
    time: "15 min ago",
  },
  {
    id: "a-2",
    type: "traffic",
    title: "Heavy Traffic on NH-48",
    message: "Severe congestion near Dhaula Kuan, expect 35-40 min additional delay",
    severity: "critical",
    time: "5 min ago",
  },
  {
    id: "a-3",
    type: "weather",
    title: "Weather Advisory - Delhi NCR",
    message: "Light rain expected from 6 PM. Consider leaving earlier to avoid waterlogging",
    severity: "info",
    time: "1 hour ago",
  },
];

export const DEMO_NOTIFICATIONS = [
  {
    id: "n-1",
    type: "transit",
    title: "Metro running on time",
    message: "Your 9:15 AM Rajiv Chowk → Sikanderpur route is running as scheduled",
    isRead: false,
    isCritical: false,
    time: "8:50 AM",
  },
  {
    id: "n-2",
    type: "traffic",
    title: "Traffic alert on your route",
    message: "Heavy traffic detected near IFFCO Chowk. Metro recommended today.",
    isRead: false,
    isCritical: true,
    time: "8:30 AM",
  },
  {
    id: "n-3",
    type: "eco",
    title: "Eco Streak: 7 days! 🌱",
    message: "You've taken eco-friendly transport for 7 consecutive days. Keep it up!",
    isRead: true,
    isCritical: false,
    time: "Yesterday",
  },
  {
    id: "n-4",
    type: "expense",
    title: "Monthly expense summary",
    message: "You spent ₹2,340 on travel this month — ₹480 less than last month",
    isRead: true,
    isCritical: false,
    time: "2 days ago",
  },
];

export const DEMO_JOURNEY_HISTORY = [
  {
    id: "j-1",
    date: "Today, 9:15 AM",
    from: "Connaught Place",
    to: "DLF Cyber City",
    mode: "Metro",
    duration: 42,
    distance: 18.2,
    cost: 60,
    co2Kg: 0.746,
    status: "completed",
  },
  {
    id: "j-2",
    date: "Yesterday, 6:30 PM",
    from: "DLF Cyber City",
    to: "Connaught Place",
    mode: "Metro",
    duration: 45,
    distance: 18.2,
    cost: 60,
    co2Kg: 0.746,
    status: "completed",
  },
  {
    id: "j-3",
    date: "Yesterday, 9:00 AM",
    from: "Connaught Place",
    to: "DLF Cyber City",
    mode: "Metro",
    duration: 40,
    distance: 18.2,
    cost: 60,
    co2Kg: 0.746,
    status: "completed",
  },
  {
    id: "j-4",
    date: "2 days ago",
    from: "Rohini West",
    to: "AIIMS Delhi",
    mode: "Metro",
    duration: 55,
    distance: 24.1,
    cost: 70,
    co2Kg: 0.988,
    status: "completed",
  },
  {
    id: "j-5",
    date: "3 days ago",
    from: "Connaught Place",
    to: "DLF Cyber City",
    mode: "Cab",
    duration: 38,
    distance: 21.8,
    cost: 320,
    co2Kg: 3.728,
    status: "completed",
  },
];
